
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Mon Jan 26 19:11:14 CET 2026
//----------------------------------------------------

package rs.ac.bg.etf.pp1;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int SQUAREOPENBRACKET = 9;
  public static final int LESSTHEN = 29;
  public static final int CONST = 5;
  public static final int CURLYOPENBRACKET = 3;
  public static final int QUESTIONMARK = 23;
  public static final int CASE = 43;
  public static final int CONTINUE = 38;
  public static final int SQUARECLBRACKET = 10;
  public static final int FOR = 44;
  public static final int MINUS = 18;
  public static final int CHARACTER = 48;
  public static final int SEMICOLON = 7;
  public static final int AND = 31;
  public static final int OR = 32;
  public static final int BOOL = 47;
  public static final int COMMA = 8;
  public static final int INC = 33;
  public static final int DIV = 21;
  public static final int DIFFERENT = 26;
  public static final int PLUS = 17;
  public static final int IF = 35;
  public static final int ASSIGN = 6;
  public static final int DOT = 15;
  public static final int EOF = 0;
  public static final int RETURN = 39;
  public static final int EQUAL = 25;
  public static final int NEW = 22;
  public static final int error = 1;
  public static final int MUL = 20;
  public static final int PERCENT = 19;
  public static final int NUMBER = 46;
  public static final int CLBRACKET = 14;
  public static final int IDENT = 45;
  public static final int BREAK = 37;
  public static final int VOID = 12;
  public static final int SWITCH = 42;
  public static final int COLON = 24;
  public static final int GREATERTHEN = 27;
  public static final int ELSE = 36;
  public static final int OPENBRACKET = 13;
  public static final int READ = 40;
  public static final int ENUM = 11;
  public static final int GREATERTHENOREQUAL = 28;
  public static final int PROG = 2;
  public static final int LESSTHENOREQUAL = 30;
  public static final int DEC = 34;
  public static final int CURLYCLBRACKET = 4;
  public static final int PRINT = 41;
  public static final int LENGTH = 16;
}

