
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Sun Feb 15 12:45:07 CET 2026
//----------------------------------------------------

package rs.ac.bg.etf.pp1;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int MONKEY = 9;
  public static final int SQUAREOPENBRACKET = 10;
  public static final int LESSTHEN = 30;
  public static final int CONST = 5;
  public static final int CURLYOPENBRACKET = 3;
  public static final int QUESTIONMARK = 24;
  public static final int CASE = 44;
  public static final int CONTINUE = 39;
  public static final int SQUARECLBRACKET = 11;
  public static final int FOR = 45;
  public static final int MINUS = 19;
  public static final int CHARACTER = 49;
  public static final int SEMICOLON = 7;
  public static final int AND = 32;
  public static final int OR = 33;
  public static final int BOOL = 48;
  public static final int COMMA = 8;
  public static final int INC = 34;
  public static final int DIV = 22;
  public static final int DIFFERENT = 27;
  public static final int PLUS = 18;
  public static final int IF = 36;
  public static final int ASSIGN = 6;
  public static final int DOT = 16;
  public static final int EOF = 0;
  public static final int RETURN = 40;
  public static final int EQUAL = 26;
  public static final int NEW = 23;
  public static final int error = 1;
  public static final int MUL = 21;
  public static final int PERCENT = 20;
  public static final int NUMBER = 47;
  public static final int CLBRACKET = 15;
  public static final int IDENT = 46;
  public static final int BREAK = 38;
  public static final int VOID = 13;
  public static final int SWITCH = 43;
  public static final int COLON = 25;
  public static final int GREATERTHEN = 28;
  public static final int ELSE = 37;
  public static final int OPENBRACKET = 14;
  public static final int READ = 41;
  public static final int ENUM = 12;
  public static final int GREATERTHENOREQUAL = 29;
  public static final int PROG = 2;
  public static final int LESSTHENOREQUAL = 31;
  public static final int DEC = 35;
  public static final int CURLYCLBRACKET = 4;
  public static final int PRINT = 42;
  public static final int LENGTH = 17;
}

